### ISSUE TITLE
Errore css

### ISSUE THREAD

**Issue by blitz69** [LDAV/woocommerce-pdf-italian-add-on#18]
Sulla scelta fattura --- ricevuta 
il dropdown menu' sulla form non si apre del tutto a causa di un comando inline (width:75%) da modificare allego foto

grazie
![Cattura](https://user-images.githubusercontent.com/64076085/79857887-c2079580-83ce-11ea-9870-b9c74ceab56a.PNG)

**Comment by LDAV** [comment]
si tratta, molto probabilmente, di una istruzione del tema.
Si può correggere con una istruzione css.

**Comment by niccolobusato** [comment]
```css
span.select2.select2-container.select2-container--default {width:100%!important;}
```

se ti può essere di aiuto
